# PRODUCTS
PRODUCTS_DEFAULT_RNG = 4242
PRODUCTS_DEFAULT_N_DIGITS_IN_NAME = 5

# STOCKS
STOCKS_DEFAULT_RNG = 4232
STOCKS_DEFAULT_N_DIGITS_IN_NAME = 5

# HUMANS
HUMANS_DEFAULT_RNG = 32
HUMANS_DEFAULT_N_DIGITS_IN_NAME = 5

# SHOPS

SHOP_DEFAULT_RNG = 42
